
name: firebase_authentication_flutter
description: AS-11 Event Registration app using Firebase Auth + local SQLite storage
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
