// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU0ahKAZaOKINCUtKSy6U_QyoEuzWQJHw',
    appId: '1:165232553201:web:f0fad85805823ca882cd50',
    messagingSenderId: '165232553201',
    projectId: 'authentication-flutter-6d031',
    authDomain: 'authentication-flutter-6d031.firebaseapp.com',
    storageBucket: 'authentication-flutter-6d031.firebasestorage.app',
    measurementId: 'G-6Y0DSKFSS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtTAZ7_n4dam1jyxVJSkiadiX-RFZ6-XY',
    appId: '1:165232553201:android:3d12ebd2c7c7627f82cd50',
    messagingSenderId: '165232553201',
    projectId: 'authentication-flutter-6d031',
    storageBucket: 'authentication-flutter-6d031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczEy6eGoiX1BrVJwwDO8xvxmBeKTDKg0',
    appId: '1:165232553201:ios:493751d63c4af5ab82cd50',
    messagingSenderId: '165232553201',
    projectId: 'authentication-flutter-6d031',
    storageBucket: 'authentication-flutter-6d031.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthenticationFlutter',
  );
}
